name: hikabrain
version: '${version}'
main: fr.zuhowks.hikabrain.Hikabrain
api-version: '1.20'
load: POSTWORLD

commands:
  ah:
    description: Admin command of Hikabrain
    usage: /ah
    permission: hikabrain.admin

permissions:
  hikabrain.admin:
    default: op
    description: admin permission